const $=id=>document.getElementById(id);const DEMO_PASSWORD="tejas";
function unlock(){if($("password").value===DEMO_PASSWORD){sessionStorage.setItem("greetingUnlocked","1");$("lock").hidden=true;$("world").hidden=false;build();tick()}else{$("error").textContent="Incorrect password.";}}
function lock(){sessionStorage.removeItem("greetingUnlocked");$("world").hidden=true;$("lock").hidden=false;$("password").value=""}
function period(){let h=new Date().getHours();return h>=5&&h<12?"morning":h>=12&&h<17?"afternoon":h>=17&&h<21?"evening":"night"}
const copy={morning:["Good Morning, Tejas!","A fresh day is waiting for you. 🌅"],afternoon:["Good Afternoon, Tejas!","Keep going — you're doing great. ☀️"],evening:["Good Evening, Tejas!","Slow down, breathe, and enjoy the evening. 🌇"],night:["Good Night, Tejas!","Rest well. Tomorrow is another adventure. 🌙"]};
function build(){let p=period();$("world").className="world "+p;$("greeting").textContent=copy[p][0];$("subtitle").textContent=copy[p][1];$("stars").innerHTML="";$("birds").innerHTML="";$("sparkles").innerHTML="";$("flowers").innerHTML="";
if(p==="night"){for(let i=0;i<65;i++){let s=document.createElement("i");s.className="star";s.style.left=Math.random()*100+"%";s.style.top=Math.random()*70+"%";s.style.animationDelay=-Math.random()*3+"s";$("stars").append(s)}for(let i=0;i<9;i++){let s=document.createElement("i");s.className="spark";s.style.left=Math.random()*100+"%";s.style.top=30+Math.random()*45+"%";$("sparkles").append(s)}}else{for(let i=0;i<3;i++){let b=document.createElement("span");b.className="bird";b.textContent="⌁";b.style.top=15+Math.random()*28+"%";b.style.animationDelay=-Math.random()*12+"s";$("birds").append(b)}}
for(let i=0;i<15;i++){let f=document.createElement("i");f.className="flower";f.style.left=2+i*7+Math.random()*3+"%";f.style.animationDelay=-Math.random()*2+"s";f.style.setProperty("--flower",["#ffd1e1","#ffe7a3","#d7c7ff","#fff"][i%4]);$("flowers").append(f)}}
function tick(){let d=new Date();$("date").textContent=d.toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});$("time").textContent=d.toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit",second:"2-digit"});if(!$("world").classList.contains(period()))build();setTimeout(tick,500)}
$("unlock").onclick=unlock;$("password").onkeydown=e=>{if(e.key==="Enter")unlock()};$("relock").onclick=lock;
if(sessionStorage.getItem("greetingUnlocked")==="1"){$("lock").hidden=true;$("world").hidden=false;build();tick()}